spring.application.name=quizapp_microservices

spring.datasource.url=jdbc:postgresql://localhost:5444/questionDB
spring.datasource.username=postgres
spring.datasource.password=db1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true
spring.jpa.show-sql=true

